"""Database creation

Revision ID: 1057ab428d86
Revises: 
Create Date: 2023-12-16 14:56:25.919468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1057ab428d86'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrator',
    sa.Column('administrator_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('surname', sa.String(length=128), nullable=False),
    sa.Column('login', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('ROLE_USER', 'ROLE_ADMIN', name='roles'), nullable=True),
    sa.PrimaryKeyConstraint('administrator_id')
    )
    op.create_table('default_user',
    sa.Column('default_user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('surname', sa.String(length=128), nullable=False),
    sa.Column('login', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('ROLE_USER', 'ROLE_ADMIN', name='roles'), nullable=True),
    sa.PrimaryKeyConstraint('default_user_id')
    )
    op.create_table('package',
    sa.Column('package_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Double(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('IN_WAREHOUSE', 'ON_WAY', 'DELIVERED', name='status'), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['default_user.default_user_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['default_user.default_user_id'], ),
    sa.PrimaryKeyConstraint('package_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('package')
    op.drop_table('default_user')
    op.drop_table('administrator')
    # ### end Alembic commands ###
