"""DB update

Revision ID: 3a71a4545dc3
Revises: 016d17f56334
Create Date: 2023-12-21 20:12:33.884292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a71a4545dc3'
down_revision: Union[str, None] = '016d17f56334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.add_column('package', sa.Column('recipient_id', sa.Integer(), nullable=True))
    op.drop_constraint('package_sender_login_fkey', 'package', type_='foreignkey')
    op.drop_constraint('package_recipient_login_fkey', 'package', type_='foreignkey')
    op.create_foreign_key(None, 'package', 'default_user', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'package', 'default_user', ['recipient_id'], ['id'])
    op.drop_column('package', 'recipient_login')
    op.drop_column('package', 'sender_login')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('sender_login', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('package', sa.Column('recipient_login', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'package', type_='foreignkey')
    op.drop_constraint(None, 'package', type_='foreignkey')
    op.create_foreign_key('package_recipient_login_fkey', 'package', 'default_user', ['recipient_login'], ['login'])
    op.create_foreign_key('package_sender_login_fkey', 'package', 'default_user', ['sender_login'], ['login'])
    op.drop_column('package', 'recipient_id')
    op.drop_column('package', 'sender_id')
    # ### end Alembic commands ###
